#!/usr/bin/env ruby
require_relative '../lib/pseudo_vasp/eam'
require_relative '../lib/pseudo_vasp/viewer'
require_relative '../lib/pseudo_vasp/two_d_view'
require 'scanf'
require 'thor'

module EAMCalc
  class CLI < Thor
    desc 'hello NAME','hello name'
    def hello(*argv)
      puts "hello #{argv}"
    end

    desc 'ev_curve','calc Energy-Volume curve with rep/bind ratio'
    def ev_curve
      system 'ruby samples/eam.rb'
    end

    desc 'show_atom FILE','show atom infor of FILE(default is 3315_inner_realx)'
    def show_atom(*argv)
      file = argv[0] || './POSCAR_0_3315_46_inner_relax_-4_1'
      $model = EAM.new(file)
      $model.show_atom
      print "\n data for atom 0\n"
      $model.show_atom_at(0)
    end

    desc 'view', 'viewing example for eam analyser'
    def view(*argv)
      puts "view options:\n  1st for  unit(0) or periodic(1), default 0,"
      puts "  2nd in nl, ene, ratio, default ene."
      file = argv[0] || './POSCAR_0_3315_46_inner_relax_-4_1'
      extend_switch = argv[1].to_i || 0
      ene_switch = argv[2] || 'ene'

      $model = EAM.new( file )
      @view = TwoDView.new( $model.return_data )
      @view.set_data( x_lat: $model.lt[0], y_lat: $model.lt[1], cx: 20, scale: 4 )
      @view.draw_atom_by_val( extend_switch, :val => ene_switch.intern )
      @view.finish
      system('open -a safari view.svg')
    end
  end
end

EAMCalc::CLI.start(ARGV)
